### ISSUE TITLE
Failed to save image

### ISSUE THREAD

**Issue by HiperGabor** [hurlenko/mloader#2]
Hello!
I get this error while using this command: **_mloader 1002187_**

11.06.2020 15:30:17 |   INFO   |   mloader.py   164  | Started export
11.06.2020 15:30:18 |  ERROR   |   mloader.py   171  | Failed to save images
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 169, in main
    loader.save(out_dir, RawExporter if raw else CBZExporter)
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 123, in save
    exporter: ExporterBase = exporter_cls(dst, title, chapter_name)
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 69, in __init__
    self.path.mkdir(parents=True, exist_ok=True)
  File "c:\python38\lib\pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
NotADirectoryError: [WinError 267] Érvénytelen a könyvtárnév: 'mangaplus_downloads\\Samurai 8: The Tale of Hachimaru'
11.06.2020 15:30:18 |   INFO   |   mloader.py   172  | SUCCESS

And **this** error while using this command: **_mloader -r 1002187_**

11.06.2020 15:31:54 |   INFO   |   mloader.py   164  | Started export
11.06.2020 15:31:56 |  ERROR   |   mloader.py   171  | Failed to save images
Traceback (most recent call last):
  File "c:\python38\lib\pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] A fájlnév, a könyvtárnév vagy a kötetcímke szintaxisa nem megfelelő: 'mangaplus_downloads\\Samurai 8: The Tale of Hachimaru\\#001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 169, in main
    loader.save(out_dir, RawExporter if raw else CBZExporter)
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 123, in save
    exporter: ExporterBase = exporter_cls(dst, title, chapter_name)
  File "c:\python38\lib\site-packages\mloader\mloader.py", line 52, in __init__
    self.path.mkdir(parents=True, exist_ok=True)
  File "c:\python38\lib\pathlib.py", line 1293, in mkdir
    if not exist_ok or not self.is_dir():
  File "c:\python38\lib\pathlib.py", line 1403, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "c:\python38\lib\pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] A fájlnév, a könyvtárnév vagy a kötetcímke szintaxisa nem megfelelő: 'mangaplus_downloads\\Samurai 8: The Tale of Hachimaru\\#001'
11.06.2020 15:31:56 |   INFO   |   mloader.py   172  | SUCCESS

**Comment by hurlenko** [comment]
The problem was that the file path contained invalid characters. Should be fixed now. Update mloader by running `pip install -U mloader` and try again.

**Comment by HiperGabor** [comment]
It's working now, thanks for fixing! Keep up the good work!
