### ISSUE TITLE
Fails to get chapter list from title (develop branch)

### ISSUE THREAD

**Issue by LegendsOfDogs** [hurlenko/mloader#44]
**Describe the bug**
As stated in the title, it fails to get chapter ids when trying to download an entire title.

**Arguments:**
`
-t 100235 -r
`

**Output:**
```
03.04.2023 01:49:40 |   INFO   |  __main__.py   206  | Started export
03.04.2023 01:49:42 |  ERROR   |  __main__.py   223  | Failed to download manga
Traceback (most recent call last):
  File "C:\Users\{redacted}\mloader\__main__.py", line 215, in main
    loader.download(
  File "C:\Python311\Lib\site-packages\mloader\loader.py", line 191, in download
    manga_list = self._normalize_ids(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\mloader\loader.py", line 115, in _normalize_ids
    details.chapter_list_group.first_chapter_list,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TitleDetailView' object has no attribute 'chapter_list_group'
03.04.2023 01:49:42 |   INFO   |  __main__.py   224  | SUCCESS
```

**Environment:**
 - OS: Windows 11 x64
 - Python version: python 3.11.0 x64
 - mloader version: 1.1.9 dev branch ([117689c](https://github.com/hurlenko/mloader/commit/117689ccdf9c32fe1f4840cb5c11fc0ba759a400))
 - Mangaplus URL: any title

**Comment by LegendsOfDogs** [comment]
solved
