### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by okanemochi241** [hurlenko/mloader#55]
Hello,

I would like to download this limited-time free manga, but I encountered an error. I am using pip3. Does this have anything to do with the pip version? Here is the error message. 

`mloader --chapter-subdir --chapter-title -o my_manga -c 10051 https://ynjn.jp/viewer/92`

```bash
            _                 _
  _ __ ___ | | ___   __ _  __| | ___ _ __
 | '_ ` _ \| |/ _ \ / _` |/ _` |/ _ \ '__|
 | | | | | | | (_) | (_| | (_| |  __/ |
 |_| |_| |_|_|\___/ \__,_|\__,_|\___|_|

25.01.2024 17:12:05 |   INFO   |  __main__.py   206  | Started export
25.01.2024 17:12:06 |   INFO   |   loader.py    138  | 1/1) Manga: 
25.01.2024 17:12:06 |   INFO   |   loader.py    139  |     Author: 
25.01.2024 17:12:06 |  ERROR   |  __main__.py   226  | Failed to download manga
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mloader/__main__.py", line 218, in main
    loader.download(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mloader/loader.py", line 189, in download
    self._download(manga_list)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mloader/loader.py", line 144, in _download
    chapter = viewer.pages[-1].last_page.current_chapter
              ~~~~~~~~~~~~^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/protobuf/internal/containers.py", line 93, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
IndexError: list index out of range
25.01.2024 17:12:06 |   INFO   |  __main__.py   227  | SUCCESS
```

manga url is : https://ynjn.jp/viewer/92/10051

**Comment by okanemochi241** [comment]
SORRY，I finally recognize my url is not supported，issue closeed.
