### ISSUE TITLE
mloader not compatible with newly added german language manga

### ISSUE THREAD

**Issue by bust4cap** [hurlenko/mloader#58]
**Stack trace**
03.03.2024 16:24:39 |  ERROR   |  __main__.py   226  | Failed to download manga
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\__main__.py", line 218, in main
    loader.download(
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\loader.py", line 189, in download
    self._download(manga_list)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\loader.py", line 154, in _download
    exporter = self.exporter(
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\exporter.py", line 140, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\exporter.py", line 47, in __init__
    self._chapter_prefix = self._format_chapter_prefix(
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\mloader\exporter.py", line 70, in _format_chapter_prefix
    if Language(language) != Language.eng:
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 7 is not a valid Language

**Environment:**
 - mloader version: 1.1.11
 - Mangaplus URL: https://mangaplus.shueisha.co.jp/titles/800001

**Comment by Saint-Devil** [comment]
Found a Solution:
Open constants.py ( %localappdata%\Programs\Python\Python312\Lib\site-packages\mloader )
in the class Language add:
    ger = 7

This worked for me :)

**Comment by IrvanFza** [comment]
Hi, I just create a pull request to solve this issue, let's wait for the maintainer to approve it.

https://github.com/hurlenko/mloader/pull/59

**Comment by hurlenko** [comment]
Fixed in #59, available in mloader v1.1.12
